'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Data&gt;
        '''  &lt;Race Name=&quot;Imperium_1&quot;&gt;
        '''    &lt;Chapter Name=&quot;General&quot;&gt;
        '''      &lt;SoloUnit&gt;
        '''        &lt;Group Name=&quot;Captain&quot;&gt;
        '''          &lt;UnitName&gt;Captain&lt;/UnitName&gt;
        '''          &lt;MinNumber&gt;1&lt;/MinNumber&gt;
        '''          &lt;MaxNumber&gt;1&lt;/MaxNumber&gt;
        '''        &lt;/Group&gt;
        '''        &lt;Group Name=&quot;Captain_in_Terminator_Armour&quot;&gt;
        '''          &lt;UnitName&gt;Captain in Terminator Armour&lt;/UnitName&gt;
        '''          &lt;MinNumber&gt;1&lt;/MinNumber&gt;
        '''          &lt;MaxNumber&gt;1&lt;/MaxNumber&gt;
        '''        &lt;/Group&gt;
        '''        &lt;Group Name=&quot;Captain_in_Cataphractii_Armour&quot;&gt;
        '''        [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Groups___Units() As String
            Get
                Return ResourceManager.GetString("Groups___Units", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property square_rounded_512_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("square_rounded_512_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property square_rounded_512_brown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("square_rounded_512_brown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property square_rounded_512_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("square_rounded_512_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property square_rounded_512_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("square_rounded_512_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Captain,1.25,1.25,6,2,2,4,4,5,4,9,3
        '''Captain in Terminator Armour,1.5,1.5,5,2,2,4,4,6,4,9,2
        '''Captain in Cataphractii Armour,1.5,1.5,4,2,2,4,4,6,4,9,2
        '''Captain in Gravis Armour,1.5,1.5,5,2,2,4,5,6,5,9,3
        '''Captain on Bike,2.75,1,14,2,2,4,5,6,4,9,3
        '''Librarian,1.25,1.25,6,3,3,4,4,4,3,9,3
        '''Librarian in Terminator Armour,1.5,1.5,5,3,3,4,4,5,3,9,2
        '''Librarian on Bike,2.75,1,14,3,3,4,5,5,3,9,3
        '''Techmarine,1.25,1.25,6,3,2,4,4,4,3,8,2
        '''Servitor,1,1,5,5,5,3,3,1,1,6,4
        '''Techmarine on Bike,2.75,1,14,3,2,4,5,5,3,8,2
        '''Chapla [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Units_Info_for_WH40K() As String
            Get
                Return ResourceManager.GetString("Units_Info_for_WH40K", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
